version: 2.1

defaults_node: &defaults_node
  docker:
    - image: circleci/node:10
  working_directory: /tmp/build

jobs:
  install_dependencies:
    <<: *defaults_node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
          environment:
            YARN_CACHE_FOLDER: /tmp/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /tmp/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .

  bootstrap:
    <<: *defaults_node
    steps:
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Bootstrap
          command: yarn bootstrap

  test:
    <<: *defaults_node
    steps:
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Run tests
          command: yarn test --coverage --runInBand

  lint:
    <<: *defaults_node
    steps:
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Run linting
          command: yarn lint

  typecheck:
    <<: *defaults_node
    steps:
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Run typechecking
          command: yarn typecheck

workflows:
  version: 2
  build-test:
    jobs:
      - install_dependencies
      - bootstrap:
          requires:
            - install_dependencies
      - test:
          requires:
            - bootstrap
      - lint:
          requires:
            - bootstrap
      - typecheck:
          requires:
            - bootstrap
