name: Auto label pull request
on: [pull_request]
jobs:
  autolabel:
    name: Auto label
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Auto label
      uses: lightspeedretail/actions-auto-label@v1-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
